# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            blog
tagline:          'buremba'
description:      'buremba'
url:              http://buremba.com
baseurl:          /

author:
  name:           'Burak Emre Kabakcı'
  url:            https://twitter.com/bu7emba

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/buremba

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'